apiVersion: apigeeregistry/v1
kind: DisplaySettings
metadata:
  name: apihub-display-settings
data:
  description: Defines display settings for the API hub UI
  organization: Registry Eval
  apiGuideEnabled: false
  apiScoreEnabled: true
