apiVersion: apigeeregistry/v1
kind: ScoreDefinition
metadata:
  name: apihub-lint-errors
data:
  displayName: Lint Errors
  description: Number of lint errors found in the API spec
  uri: https://meta.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules
  uriDisplayName: Spectral rules
  targetResource:
    pattern: apis/-/versions/-/specs/-
    filter: ""
  scoreFormula:
    artifact:
      pattern: $resource.spec/artifacts/conformance-apihub-styleguide
      filter: ""
    scoreExpression: 'has(guidelineReportGroups[2].guidelineReports) ? sum(guidelineReportGroups[2].guidelineReports.map(r, has(r.ruleReportGroups[1].ruleReports) ? size(r.ruleReportGroups[1].ruleReports) : 0)) : 0'
    referenceId: ""
  integer:
    minValue: 0
    maxValue: 100
    thresholds: []
